version: 2.1
jobs:
  install:
    docker:
        - image: 'cimg/node:15.3.0'
      resource_class: small
      steps:
        - checkout
        - run: npm install
  build:
    docker:
        - image: 'cimg/node:15.3.0'
      resource_class: small
      steps:
        - run: ./node_modules/.bin/tsc
  test:
    docker:
      - image: 'cimg/node:15.3.0'
    resource_class: small
    steps:
      - run: npm run test

workflows:
  test_module:
    jobs:
    - build
    - test